#!/bin/bash

read -p "Введите путь к Вашему файлу: " folder_path
if [ ! -e "$folder_path" ]; then
    echo "Ошибка, файл не существует или не является файлом"
    exit 1
fi 

#размер раздела в битах
total_disk_size=$(df -B1 "$folder_path" | awk 'NR==2 {print $2}')

#размер папки в битах
folder_size=$(du -sb "$folder_path" | cut -f1)

#процент который занимает папка
procentage=$(echo "scale=2; $folder_size*100 / $total_disk_size" | bc)
#максимальный процент, после которого идет архивация
maxprocentage=70

echo "=== ИНФОРМАЦИЯ О ПАПКЕ И РАЗДЕЛЕ ЙОУ ==="
echo "Размер всего раздела: $(df -h "$folder_path" | awk 'NR==2 {print $2}')"
echo "Размер папки: $(du -sh "$folder_path" | cut -f1)"
echo "Папка занимает: $procentage% от раздела"

if [ $(echo "$procentage > $maxprocentage" | bc) -eq 1 ]; then
    echo "Файл больше допустимого максимального размера, произвожу архивацию"
else
    echo "Файл допустимого размера"
fi
